[[tier]]
tasks = ["mn-3221"]

[[tier]]
tasks = ["mn-7qet"]

[[tier]]
tasks = [
    "mn-8xpc",
    "mn-qe7b",
    "mn-kau5",
    "mn-eyet",
]

[[tier]]
tasks = ["mn-6dbp"]

[[tier]]
tasks = ["mn-cru4"]

[[tier]]
tasks = ["mn-kbfa"]

[[tier]]
tasks = ["mn-hsxc"]

[[tier]]
tasks = ["mn-s36r"]
